### ISSUE TITLE
请问这个还在更新吗？

### ISSUE THREAD

**Issue by mcck** [WeJoy/HJMirror#1]

**Comment by wejoy** [comment]
更新的，在用Go和Qt重写，进度70%吧，能用了就提交

**Comment by wejoy** [comment]
UI改为使用andlabs库，Qt与Go Modules结合使用起来不是很方便，另外还有LICENSE问题，改用MIT协议的andlabs，目前看上去没啥太大问题。

**Comment by bigbigpeng3** [comment]
@wejoy 这个项目还在维护吗？请问有联系方式吗，邮箱就好了，公开微信/QQ不好。这个项目我也想参与，目前的想法就是做一个广域网能够实现远程控制的App。当然，服务器还是需要自己搭建的。我自己也是4年的Android开发。对这一块还是比较感兴趣的。可以的话，可以一起沟通/开发。

**Comment by wejoy** [comment]
> 
> 
> @wejoy 这个项目还在维护吗？请问有联系方式吗，邮箱就好了，公开微信/QQ不好。这个项目我也想参与，目前的想法就是做一个广域网能够实现远程控制的App。当然，服务器还是需要自己搭建的。我自己也是4年的Android开发。对这一块还是比较感兴趣的。可以的话，可以一起沟通/开发。

## 新版项目发展说明

还维护的，我目前也有加个局域网或广域网远程功能的想法，用host程序做个中转，最近比较忙，快半年没更新了，只是本地陆续做了些更新，目前新方向是用go重写项目，另外在研究是不是能用WASM做client端，把项目划分为3个部分：

Android 设置APP + adb启动插件 + 输入法： 输入法用于映射键盘输入到Android设备，ADB插件用于截屏和事件模拟及与HOST交互。

Host 服务： 使用 Go 实现，Android 设备通过USB连接在HOST上，然后HOST服务的作用是中转数据。

Client UI： 使用 WASM 实现，通过浏览器远程访问Host服务，获得WASM包，启动后连接HOST 服务获得Android设备交互。

未来可能还会为HOST服务添加HTTP代理，实现HTTP抓包，接口MOCK等功能，把我另一个项目Mocktool的功能整合到HOST服务上。

## 目前新版开发进度：

1、完成了Go下载、调用ADB的模块，功能基本正常

2、完成了一个Qt的GUI界面，但不是很满意，目前没找到一个合适的Go GUI框架

3、Android 输入法，有个雏形，没全部完成

## 目前主要问题：

1、还没实现Go和Android Java间一个比较好的图像传输，我对视频流传输了解基本为0，目前图像传输使用很水的全帧JPEG+减小分辨率JPEG传输的，想找到种不会影响传输延时，但又能提高码率增加帧率的方式。

2、对WASM不太熟悉，用Go做WASM打的包太大，但又不会Rust，C/C++构建太麻烦不用，这个问题目前还比较纠结。

3、没给这项目找到一个比较好的出路，想不出这东西有什么用，可能未来只能用在类似testin云测或者自动化测试上面，但这个和虚拟机相比貌似没什么优势。

### 联系方式：halfmanhuang@hjess.com
