### ISSUE TITLE
能不能直接发布下版本,直接能用的

### ISSUE THREAD

**Issue by xman55555** [WeJoy/HJMirror#3]
不会搞 安卓开发环境............

**Comment by wejoy** [comment]
已经新增了一个Java 2.0.0版的Release
[https://github.com/wejoy/HJMirror/releases](https://github.com/wejoy/HJMirror/releases)

就一个jar包，下载后用java执行即可

**Comment by xman55555** [comment]
谢谢大佬,如果是wifi 能不能用呢? 就是局域网控制

**Comment by wejoy** [comment]
> 
> 
> 谢谢大佬,如果是wifi 能不能用呢? 就是局域网控制

现在还不行，手机必须通过adb连接到pc上，ADBWifi可能也可以我没试过

后续会添加一种方式就是：
1、手机插在一台pc上
2、然后和该PC在同一个局域网内的另一台PC可以访问
