### ISSUE TITLE
Android9无法启动截屏

### ISSUE THREAD

**Issue by YZhu2022** [WeJoy/HJMirror#4]
https://cdn.discordapp.com/attachments/589110147117481987/609785202964955149/Annotation_2019-08-11_002739.jpg
这是运行的截图 没有找到log文件没法报错
使用的手机为Android 9 
手机端显示服务运行

**Comment by wejoy** [comment]
Android 9我没测试过，我有时间看下~~

**Comment by wejoy** [comment]
问题推断为Android 9.0截屏方法变更为：
```java
public static Bitmap screenshot(Rect sourceCrop, int width, int height,
    int minLayer, int maxLayer, boolean useIdentityTransform,
    int rotation) {
```
修正中

**Comment by wejoy** [comment]
> 
> 
> https://cdn.discordapp.com/attachments/589110147117481987/609785202964955149/Annotation_2019-08-11_002739.jpg
> 这是运行的截图 没有找到log文件没法报错
> 使用的手机为Android 9
> 手机端显示服务运行

Android9截屏问题已修正，更新到2.0.1，release同更新至2.0.1
但Android9远控无效问题尚未解决，方案研究中
https://github.com/wejoy/HJMirror/tree/2.0.1


更新：

Android9远控确认无问题，Android10也已经测试，但确认小米Android9以上系统存在远控失效问题
另开一个BUG：https://github.com/wejoy/HJMirror/issues/5
